### ISSUE TITLE
May I know how to switch carmera selection from back to front

### ISSUE THREAD

**Issue by brandesyeh** [facundomedica/fast_qr_reader_view#25]

**Comment by brandesyeh** [comment]
It seems not work. When I change   the following
// pick the first available camera
    onNewCameraSelected(cameras[1]);
or
    // pick the first available camera
    onNewCameraSelected(cameras[0]);

It always use the back camera.

Thanks all.

**Comment by brandesyeh** [comment]
Appreciate for any suggestion or comment。I really need to know how to use Front Camera for QRCode Scan. Thanks!

**Comment by hilfritz** [comment]
I have the same problem.

**Comment by adlanarifzr** [comment]
The latest versions should be working.

**Comment by marlongb** [comment]
I am using this version fast_qr_reader_view: ^ 0.1.5 and still does not work.

**Comment by Sadoge** [comment]
If you use the latest version like this, it works fine again

```
fast_qr_reader_view: 
     git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
```
